/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Interface_Imp.employee;
import javax.swing.JFrame;
import javax.swing.JPanel;
import systemmanagmentship.Tools;

/**
 *
 * @author User
 */
public class addEmployee extends javax.swing.JFrame {

    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        search_by = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        number = new javax.swing.JRadioButton();
        namee = new javax.swing.JRadioButton();
        typej = new javax.swing.JRadioButton();
        no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        update = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        showadd = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_work = new javax.swing.JTable();
        add = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        delet = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 139));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 139));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 213, 252));
        jLabel1.setText("Employee No:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 90, 28));

        jLabel2.setBackground(new java.awt.Color(0, 0, 139));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 213, 252));
        jLabel2.setText("Employee Name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 139));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 213, 252));
        jLabel3.setText("Salary :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 109, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 213, 252));
        jLabel4.setText("Address :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 122, 25));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Cancelnn_32.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Go_Back_32.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Minusjj_32.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel2.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        search_by.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_S_32.png"))); // NOI18N
        search_by.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_by.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_byMouseClicked(evt);
            }
        });
        jPanel2.add(search_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 55, -1, 35));

        search.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        search.setForeground(new java.awt.Color(210, 213, 252));
        search.setText("Search By :");
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 100, 29));

        search1.setBackground(new java.awt.Color(0, 0, 139));
        search1.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252), 2));
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel2.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 55, 211, 35));

        number.setBackground(new java.awt.Color(0, 0, 139));
        number.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        number.setForeground(new java.awt.Color(210, 213, 252));
        number.setSelected(true);
        number.setText("Number");
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel2.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        namee.setBackground(new java.awt.Color(0, 0, 139));
        namee.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        namee.setForeground(new java.awt.Color(210, 213, 252));
        namee.setText("Name");
        namee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeActionPerformed(evt);
            }
        });
        jPanel2.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        typej.setBackground(new java.awt.Color(0, 0, 139));
        typej.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        typej.setForeground(new java.awt.Color(210, 213, 252));
        typej.setText("Type Job");
        jPanel2.add(typej, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 90, -1));

        no.setEditable(false);
        no.setBackground(new java.awt.Color(0, 0, 139));
        no.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 213, 252), 2, true));
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
        });
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel2.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 64, 186, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(210, 213, 252));
        jLabel5.setText("Type Job :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 109, 29));

        name.setBackground(new java.awt.Color(0, 0, 139));
        name.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252), 2));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 101, 186, 28));

        address.setBackground(new java.awt.Color(0, 0, 139));
        address.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252), 2));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 135, 186, 28));

        salary.setBackground(new java.awt.Color(0, 0, 139));
        salary.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        salary.setForeground(new java.awt.Color(255, 255, 255));
        salary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252), 2));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel2.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 169, 186, 28));

        type.setBackground(new java.awt.Color(0, 0, 139));
        type.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252), 2));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 208, 186, 28));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 260));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Change_Us.png_48.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 139));
        jLabel11.setText("Update");

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(37, 37, 37))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        showadd.setBackground(new java.awt.Color(255, 255, 255));
        showadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        showadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showaddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showaddMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_Account_48.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 139));
        jLabel15.setText("Show All");

        javax.swing.GroupLayout showaddLayout = new javax.swing.GroupLayout(showadd);
        showadd.setLayout(showaddLayout);
        showaddLayout.setHorizontalGroup(
            showaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showaddLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(showaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        showaddLayout.setVerticalGroup(
            showaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showaddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Broom_48.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 139));
        jLabel17.setText("Clear");

        javax.swing.GroupLayout clearLayout = new javax.swing.GroupLayout(clear);
        clear.setLayout(clearLayout);
        clearLayout.setHorizontalGroup(
            clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clearLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(37, 37, 37))
        );
        clearLayout.setVerticalGroup(
            clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        labMessage.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        labMessage.setForeground(new java.awt.Color(0, 0, 139));

        jTable_Display_work.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jTable_Display_work.setForeground(new java.awt.Color(0, 0, 139));
        jTable_Display_work.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "number", "name", "Address", "Salary", "Type Job"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Display_work.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_Display_work.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable_Display_work.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_workMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_work);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Add_User_Male_48.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 139));
        jLabel19.setText(" ADD");

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        delet.setBackground(new java.awt.Color(255, 255, 255));
        delet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        delet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Denied_48.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 139));
        jLabel13.setText("Delete");

        javax.swing.GroupLayout deletLayout = new javax.swing.GroupLayout(delet);
        delet.setLayout(deletLayout);
        deletLayout.setHorizontalGroup(
            deletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(deletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        deletLayout.setVerticalGroup(
            deletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(labMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 299, 770, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked
    employee emp = new employee();
    void setvalues(){
     emp.setNo(Integer.parseInt(no.getText()));
     emp.setName(name.getText());
     emp.setAddress(address.getText());
     emp.setSalary(Integer.parseInt(salary.getText()));
     emp.setType_job(type.getText());
    }
    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new FromAdmin1());
    }//GEN-LAST:event_backMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);//أخفاء النافدة عن الشاشة
    }//GEN-LAST:event_minMouseClicked

    private void search_byMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_byMouseClicked
        // TODO add your handling code here:
        String stSearch = "select * from employee where ";
        if (number.isSelected()) {
            stSearch += "empno";
        } else if (namee.isSelected()) {
            stSearch += "empname";
        }
        else {
            stSearch += "Typejop";
        }
        stSearch += " like '%" + search1.getText() + "%'";
     database.UseDatabase.fillJTable(stSearch, jTable_Display_work);
    }//GEN-LAST:event_search_byMouseClicked

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void nameeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameeActionPerformed

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_noMouseClicked

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        resetcolor(add);
    }//GEN-LAST:event_addMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        setcolor(add);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        if(no.getText().length()==0 || name.getText().length()==0 ||address.getText().length()==0 ||salary.getText().length()==0||type.getText().length()==0   ){
            labMessage.setText("please fill fields ! ");
        }else{
        setvalues();
        emp.Add(labMessage);
        database.UseDatabase.fillJTable("select * from employee where Active=1", jTable_Display_work);
        }
    }//GEN-LAST:event_addMouseClicked

    private void jTable_Display_workMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_workMouseClicked
        int row = jTable_Display_work.getSelectedRow();
        String Number = jTable_Display_work.getValueAt(row, 0).toString();
        no.setText(Number);
        String _name = jTable_Display_work.getValueAt(row, 1).toString();
        name.setText(_name);
        String _address = jTable_Display_work.getValueAt(row, 2).toString();
        address.setText(_address);
        String _salary = jTable_Display_work.getValueAt(row, 3).toString();
        salary.setText(_salary);
        String typejob = jTable_Display_work.getValueAt(row, 4).toString();
        type.setText(typejob);
        add.setEnabled(false);
    }//GEN-LAST:event_jTable_Display_workMouseClicked

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        resetcolor(clear);
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        setcolor(clear);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        labMessage.setText("");
        search1.setText("");
        add.setEnabled(true);
        update.setEnabled(false);
        delet.setEnabled(false);
        String numb = emp.GetAutoNumber();
        no.setText(numb);
    }//GEN-LAST:event_clearMouseClicked
    public void setcolor(JPanel panel){
        panel.setBackground(new java.awt.Color(210,209,235));
    }
    public void resetcolor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }
    private void showaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showaddMouseExited
        // TODO add your handling code here:
        resetcolor(showadd);
    }//GEN-LAST:event_showaddMouseExited

    private void showaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showaddMouseEntered
        // TODO add your handling code here:
        setcolor(showadd);
    }//GEN-LAST:event_showaddMouseEntered

    private void showaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showaddMouseClicked
        // TODO add your handling code here:
        database.UseDatabase.fillJTable("select * from employee where Active=1", jTable_Display_work);
    }//GEN-LAST:event_showaddMouseClicked

    private void deletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletMouseExited
        // TODO add your handling code here:
        resetcolor(delet);
    }//GEN-LAST:event_deletMouseExited

    private void deletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletMouseEntered
        // TODO add your handling code here:
        setcolor(delet);
    }//GEN-LAST:event_deletMouseEntered

    private void deletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletMouseClicked
        setvalues();
        emp.Delete(labMessage);
        database.UseDatabase.fillJTable("select * from employee where Active=1", jTable_Display_work);
    }//GEN-LAST:event_deletMouseClicked

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        resetcolor(update);
    }//GEN-LAST:event_updateMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        setcolor(update);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        setvalues();
        emp.Update(labMessage);
        database.UseDatabase.fillJTable("select * from employee where Active=1", jTable_Display_work);
    }//GEN-LAST:event_updateMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        bg.add(namee);
        bg.add(number);
        bg.add(typej);
    database.UseDatabase.fillJTable("select * from employee where Active=1", jTable_Display_work);
    String numb = emp.GetAutoNumber();
        no.setText(numb);    
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JTextField address;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JPanel clear;
    private javax.swing.JLabel close;
    private javax.swing.JPanel delet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_work;
    private javax.swing.JLabel labMessage;
    private javax.swing.JLabel min;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton namee;
    private javax.swing.JTextField no;
    private javax.swing.JRadioButton number;
    private javax.swing.JTextField salary;
    private javax.swing.JLabel search;
    private javax.swing.JTextField search1;
    private javax.swing.JLabel search_by;
    private javax.swing.JPanel showadd;
    private javax.swing.JTextField type;
    private javax.swing.JRadioButton typej;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
