/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Forms.LOOGIN;
import systemmanagmentship.Tools;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class FromAdmin1 extends javax.swing.JFrame {

   

    /**
     * Creates new form FromAdmin1
     */
    public FromAdmin1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        SeaPort = new javax.swing.JButton();
        trip = new javax.swing.JButton();
        ship_crew = new javax.swing.JButton();
        Company = new javax.swing.JButton();
        fleet = new javax.swing.JButton();
        CompanyRental = new javax.swing.JButton();
        addemp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        exit2 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SeaPort.setBackground(new java.awt.Color(255, 255, 255));
        SeaPort.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        SeaPort.setForeground(new java.awt.Color(0, 0, 139));
        SeaPort.setText("Seaport");
        SeaPort.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeaPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeaPortActionPerformed(evt);
            }
        });

        trip.setBackground(new java.awt.Color(255, 255, 255));
        trip.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        trip.setForeground(new java.awt.Color(0, 0, 139));
        trip.setText("Trip");
        trip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tripMouseClicked(evt);
            }
        });
        trip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripActionPerformed(evt);
            }
        });

        ship_crew.setBackground(new java.awt.Color(255, 255, 255));
        ship_crew.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        ship_crew.setForeground(new java.awt.Color(0, 0, 139));
        ship_crew.setText("Ship Crew");
        ship_crew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ship_crew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ship_crewMouseClicked(evt);
            }
        });
        ship_crew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ship_crewActionPerformed(evt);
            }
        });

        Company.setBackground(new java.awt.Color(255, 255, 255));
        Company.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        Company.setForeground(new java.awt.Color(0, 0, 139));
        Company.setText("Company");
        Company.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyMouseClicked(evt);
            }
        });
        Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyActionPerformed(evt);
            }
        });

        fleet.setBackground(new java.awt.Color(255, 255, 255));
        fleet.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        fleet.setForeground(new java.awt.Color(0, 0, 139));
        fleet.setText("The Fleet");
        fleet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleetActionPerformed(evt);
            }
        });

        CompanyRental.setBackground(new java.awt.Color(255, 255, 255));
        CompanyRental.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        CompanyRental.setForeground(new java.awt.Color(0, 0, 139));
        CompanyRental.setText("Company Rental Ship");
        CompanyRental.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CompanyRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyRentalMouseClicked(evt);
            }
        });
        CompanyRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyRentalActionPerformed(evt);
            }
        });

        addemp.setBackground(new java.awt.Color(255, 255, 255));
        addemp.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        addemp.setForeground(new java.awt.Color(0, 0, 139));
        addemp.setText("Employee");
        addemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addempMouseClicked(evt);
            }
        });
        addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CompanyRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ship_crew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fleet, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(SeaPort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fleet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(SeaPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CompanyRental, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addemp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(trip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ship_crew, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 139));

        exit2.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(255, 255, 255));
        exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Cancelnn_32.png"))); // NOI18N
        exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Minusjj_32.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Go_Back_32.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit2)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addComponent(min)
                    .addComponent(exit2))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleetActionPerformed
        this.dispose();
        Tools.openForm(new FleetOpertions());//افتح شاشة الاضافة
    }//GEN-LAST:event_fleetActionPerformed

    private void SeaPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeaPortActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new SeaPortOperations());
    }//GEN-LAST:event_SeaPortActionPerformed

    private void tripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripActionPerformed

    private void ship_crewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ship_crewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ship_crewActionPerformed

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CompanyActionPerformed
       static String type;
    public static void Type(String _type) {
        type = _type;
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
           switch (type) {
            case "Admin":
                Company.setEnabled(false);
                CompanyRental.setEnabled(false);
                trip.setEnabled(false);
                ship_crew.setEnabled(false);
                addemp.setEnabled(false);
                break;
            case "Commercial Manager":
                SeaPort.setEnabled(false);
                fleet.setEnabled(false);
                ship_crew.setEnabled(false);
                addemp.setEnabled(false);
                break;
            default:
                SeaPort.setEnabled(false);
                fleet.setEnabled(false);
                trip.setEnabled(false);
                Company.setEnabled(false);
                CompanyRental.setEnabled(false);
                break;
        }
       }catch(Exception ex){
           Tools.msBox("error in formAdmin"+ ex.getMessage());
       }
           
           
    }//GEN-LAST:event_formWindowOpened

    private void CompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new F_Add_Company());
        Company.setEnabled(false);
    }//GEN-LAST:event_CompanyMouseClicked

    private void CompanyRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyRentalMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new F_Add_Rentel_ship());
    }//GEN-LAST:event_CompanyRentalMouseClicked

    private void CompanyRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyRentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyRentalActionPerformed

    private void ship_crewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ship_crewMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new workOnShip());
    }//GEN-LAST:event_ship_crewMouseClicked

    private void tripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tripMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new info_trip());
    }//GEN-LAST:event_tripMouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit2MouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);//أخفاء النافدة عن الشاشة
    }//GEN-LAST:event_minMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new LOOGIN());
    }//GEN-LAST:event_backMouseClicked

    private void addempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addempMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addempMouseClicked

    private void addempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempActionPerformed
        // TODO add your handling code here:
        Tools.openForm(new addEmployee());
    }//GEN-LAST:event_addempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromAdmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Company;
    private javax.swing.JButton CompanyRental;
    private javax.swing.JButton SeaPort;
    private javax.swing.JButton addemp;
    private javax.swing.JLabel back;
    private javax.swing.JLabel exit2;
    private javax.swing.JButton fleet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel min;
    private javax.swing.JButton ship_crew;
    private javax.swing.JButton trip;
    // End of variables declaration//GEN-END:variables
}
