
package Forms;

import Interface_Imp.trip;
import database.UseDatabase;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import systemmanagmentship.Tools;

/**
 *
 * @author User
 */
public class info_trip extends javax.swing.JFrame{

    /**
     * Creates new form info_trip
     */
    public info_trip() {
        initComponents();
        CurrentDate();
    }
     String datenow;   
     public  void CurrentDate(){
       Thread _clock = new Thread(){
     @Override
    public void run() {
            for(;;){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        datenow = day+"/"+(month+1)+"/"+year;
        datee.setText(day + "/" + (month+1) +"/"+year);
        int hour = cal.get(Calendar.HOUR);
        int min = cal.get(Calendar.MINUTE);
        int sec = cal.get(Calendar.SECOND);
        clock.setText(hour + ":" + min + ":" + sec);
        try{
            Thread.sleep(1000);
        }catch(Exception e){
            Tools.msBox(e.getMessage());
        }
        }
       }
     };
           _clock.start();
               }
 
         
                 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        update = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        showwal = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        datee = new javax.swing.JTextField();
        clock = new javax.swing.JTextField();
        Add1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Date_S = new com.toedter.calendar.JDateChooser();
        Date_E = new com.toedter.calendar.JDateChooser();
        labMessage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        trip = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loadwieght1 = new javax.swing.JTextField();
        toseaport = new javax.swing.JComboBox<>();
        companyname = new javax.swing.JComboBox<>();
        fromseaport = new javax.swing.JComboBox<>();
        shipname = new javax.swing.JComboBox<>();
        Search = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        search_by = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        timebr = new javax.swing.JRadioButton();
        tripno = new javax.swing.JRadioButton();
        br3 = new javax.swing.JRadioButton();
        br4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 139));

        update.setBackground(new java.awt.Color(0, 0, 139));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252)));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(210, 213, 252));
        jLabel19.setText("Update");
        update.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 30));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Refreshb_32.png"))); // NOI18N
        update.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 30, 30));

        delete.setBackground(new java.awt.Color(0, 0, 139));
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252)));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(210, 213, 252));
        jLabel21.setText("Archive");
        delete.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 30));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Archive_Folder_32.png"))); // NOI18N
        delete.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 30));

        showwal.setBackground(new java.awt.Color(0, 0, 139));
        showwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252)));
        showwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showwalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showwalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showwalMouseExited(evt);
            }
        });
        showwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(210, 213, 252));
        jLabel23.setText("show all");
        showwal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 50, 30));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/C_32.png"))); // NOI18N
        showwal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 30));

        clear.setBackground(new java.awt.Color(0, 0, 139));
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252)));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(210, 213, 252));
        jLabel15.setText("Clear");
        clear.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, 30));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Broomnn_32.png"))); // NOI18N
        clear.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 30));

        exit1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Cancelnn_32.png"))); // NOI18N
        exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Go_Back_32.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        datee.setEditable(false);
        datee.setBackground(new java.awt.Color(0, 0, 139));
        datee.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        datee.setForeground(new java.awt.Color(255, 255, 255));
        datee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 213, 252), 1, true));
        datee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateeMouseClicked(evt);
            }
        });
        datee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateeActionPerformed(evt);
            }
        });

        clock.setEditable(false);
        clock.setBackground(new java.awt.Color(0, 0, 139));
        clock.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));
        clock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 213, 252), 1, true));
        clock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clockMouseClicked(evt);
            }
        });
        clock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockActionPerformed(evt);
            }
        });

        Add1.setBackground(new java.awt.Color(0, 0, 139));
        Add1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252)));
        Add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add1MouseExited(evt);
            }
        });
        Add1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(210, 213, 252));
        jLabel25.setText("ADD");
        Add1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 40, 30));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Addbbb_32.png"))); // NOI18N
        Add1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showwal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(datee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showwal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Date_S.setBackground(new java.awt.Color(255, 255, 255));
        Date_S.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 139), 2, true));
        Date_S.setForeground(new java.awt.Color(0, 0, 139));
        Date_S.setToolTipText("");
        Date_S.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jPanel3.add(Date_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 230, 30));

        Date_E.setBackground(new java.awt.Color(255, 255, 255));
        Date_E.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 139), 2, true));
        Date_E.setForeground(new java.awt.Color(0, 0, 139));
        Date_E.setToolTipText("");
        Date_E.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jPanel3.add(Date_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 230, 30));

        labMessage.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        labMessage.setForeground(new java.awt.Color(0, 0, 139));
        jPanel3.add(labMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 510, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 139));
        jLabel6.setText("Trip No :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 139));
        jLabel7.setText("Return Date:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 180, 20));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 139));
        jLabel8.setText("time Trip :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 180, 30));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 139));
        jLabel9.setText("To seaport :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 180, 20));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 139));
        jLabel10.setText("ship name:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 30));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 139));
        jLabel11.setText("from seaport:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 180, 30));

        time.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 153));
        time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 139), 2, true));
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeMouseClicked(evt);
            }
        });
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 220, 30));

        trip.setEditable(false);
        trip.setBackground(new java.awt.Color(255, 255, 255));
        trip.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        trip.setForeground(new java.awt.Color(0, 0, 153));
        trip.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 139), 2, true));
        trip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tripMouseClicked(evt);
            }
        });
        trip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripActionPerformed(evt);
            }
        });
        jPanel3.add(trip, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 30));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 139));
        jLabel12.setText("Date sailng:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 180, 30));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 139));
        jLabel13.setText("load wieght :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 180, 30));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 139));
        jLabel14.setText("Company name:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "trip no", "company anme", "ship name", "from", "to", "load width", "date Sailing", "return date", "time trip"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 261, 840, 200));

        loadwieght1.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        loadwieght1.setForeground(new java.awt.Color(0, 0, 153));
        loadwieght1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 139), 2, true));
        loadwieght1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadwieght1MouseClicked(evt);
            }
        });
        loadwieght1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadwieght1ActionPerformed(evt);
            }
        });
        jPanel3.add(loadwieght1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 230, 30));

        toseaport.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        toseaport.setForeground(new java.awt.Color(0, 0, 139));
        toseaport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(toseaport, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 220, 30));

        companyname.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        companyname.setForeground(new java.awt.Color(0, 0, 139));
        companyname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        fromseaport.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        fromseaport.setForeground(new java.awt.Color(0, 0, 139));
        fromseaport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(fromseaport, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 220, 30));

        shipname.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        shipname.setForeground(new java.awt.Color(0, 0, 139));
        shipname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(shipname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 30));

        Search.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        Search.setForeground(new java.awt.Color(0, 0, 139));
        Search.setBorder(null);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 0, 139));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 139));
        jSeparator7.setAlignmentY(0.8F);

        search_by.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_32_1.png"))); // NOI18N
        search_by.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_by.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_byMouseClicked(evt);
            }
        });

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 139));
        search.setText("Search By :");

        timebr.setBackground(new java.awt.Color(255, 255, 255));
        timebr.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        timebr.setForeground(new java.awt.Color(0, 0, 139));
        timebr.setText("time trip");
        timebr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timebrActionPerformed(evt);
            }
        });

        tripno.setBackground(new java.awt.Color(255, 255, 255));
        tripno.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        tripno.setForeground(new java.awt.Color(0, 0, 139));
        tripno.setSelected(true);
        tripno.setText("Trip No");
        tripno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripnoActionPerformed(evt);
            }
        });

        br3.setBackground(new java.awt.Color(255, 255, 255));
        br3.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        br3.setForeground(new java.awt.Color(0, 0, 139));
        br3.setText("name company");

        br4.setBackground(new java.awt.Color(255, 255, 255));
        br4.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        br4.setForeground(new java.awt.Color(0, 0, 139));
        br4.setText("name ship");
        br4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(search_by)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tripno)
                                .addGap(18, 18, 18)
                                .addComponent(timebr)
                                .addGap(18, 18, 18)
                                .addComponent(br3)
                                .addGap(18, 18, 18)
                                .addComponent(br4)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timebr)
                            .addComponent(tripno)
                            .addComponent(br3)
                            .addComponent(br4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(search_by, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   java.util.Date date;
        java.sql.Date sqlDate;
    trip t = new trip();
    void setvalues(){
    t.setCompany_name((String) companyname.getSelectedItem());
    t.setShip_name((String) shipname.getSelectedItem());
    t.setFrom_seaport((String) fromseaport.getSelectedItem());
    t.setTo_seaport((String) toseaport.getSelectedItem());
    t.setTrip_no(Integer.parseInt(trip.getText()));
    t.setLoadwieght(loadwieght1.getText());
    date = Date_S.getDate();
       sqlDate = new java.sql.Date(date.getTime());
        t.setDate_s(sqlDate);
        date = Date_E.getDate();
       sqlDate = new java.sql.Date(date.getTime());
        t.setDate_e(sqlDate);
    t.setTime_trip(time.getText());
       
   }
    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked

        this.dispose();
        Tools.openForm(new FromAdmin1());
    }//GEN-LAST:event_BackMouseClicked

    private void timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_timeMouseClicked

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void tripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tripMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tripMouseClicked

    private void tripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripActionPerformed
   
     
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bg.add(br3);
        bg.add(br4);
        bg.add(tripno);
        bg.add(timebr);
        database.UseDatabase.fillJTable("select * from trip where Active = 1", jTable1);
        UseDatabase.filComboBox("select compayname from rent_ship where Active =1",companyname );
        UseDatabase.filComboBox("select shipname from rent_ship where Active = 1",shipname);
        UseDatabase.filComboBox("select seaportname from seaport where Active =1 ", fromseaport);
        UseDatabase.filComboBox("select seaportname from seaport where Active = 1",toseaport  );
        jTable1.getTableHeader().setReorderingAllowed(false);

         String numb_t = t.GetAutoNumber();
            trip.setText(numb_t);
            
    }//GEN-LAST:event_formWindowOpened

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        trip.setText("");
        time.setText("");
          String numb_t = t.GetAutoNumber();
            trip.setText(numb_t);
         
    }//GEN-LAST:event_clearMouseClicked
    public void setcolor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,0,170));
    }
    public void resetcolor(JPanel panel){
        panel.setBackground(new java.awt.Color(0,0,139));
    }
    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        setvalues();
        t.Update(labMessage);
               database.UseDatabase.fillJTable("select * from trip where Active = 1", jTable1);

    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        setvalues();
        t.Delete(labMessage);
               database.UseDatabase.fillJTable("select * from trip where Active = 1", jTable1);

    }//GEN-LAST:event_deleteMouseClicked

    private void showwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showwalMouseClicked
        // TODO add your handling code here:
        database.UseDatabase.fillJTable("select * from trip where Active=1", jTable1);
    }//GEN-LAST:event_showwalMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        setcolor(update);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        resetcolor(update);
    }//GEN-LAST:event_updateMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        setcolor(delete);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        resetcolor(delete);
    }//GEN-LAST:event_deleteMouseExited

    private void showwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showwalMouseEntered
        // TODO add your handling code here:
        setcolor(showwal);
    }//GEN-LAST:event_showwalMouseEntered

    private void showwalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showwalMouseExited
        // TODO add your handling code here:
        resetcolor(showwal);
    }//GEN-LAST:event_showwalMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        setcolor(clear);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        resetcolor(clear);
    }//GEN-LAST:event_clearMouseExited

    private void search_byMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_byMouseClicked
        // TODO add your handling code here:

        if (Search.getText().length() == 0) {
            Tools.msBox("please fill field ! ");
        } else {
            String strSearch = "select * from trip where ";
            if(tripno.isSelected()){
                strSearch+="trip_no";
            }else if(timebr.isSelected()){
                strSearch+="time_trip";
            }else if(br3.isSelected()){
                strSearch+="companyname";
            }
            else{
                strSearch+="shipname";
            }
            strSearch+=" like '%" + Search.getText() +"%'";
            database.UseDatabase.fillJTable(strSearch, jTable1);
        }
    }//GEN-LAST:event_search_byMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void tripnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripnoActionPerformed

    private void br4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_br4ActionPerformed

    private void timebrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timebrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timebrActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            int row = jTable1.getSelectedRow();
            String C_Number = jTable1.getValueAt(row, 0).toString();
            trip.setText(C_Number);
            String time_t = jTable1.getValueAt(row, 8).toString();
            this.time.setText(time_t);
            String load = jTable1.getValueAt(row, 5).toString();
            loadwieght1.setText(load);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Date date_s = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(row, 6));
            Date_S.setDate(date_s);
            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)model1.getValueAt(row, 7));
            Date_E.setDate(date1);
            String ship_s = jTable1.getValueAt(row, 2).toString();
            String f_seaport =jTable1.getValueAt(row, 3).toString();
            String t_seaport =jTable1.getValueAt(row, 4).toString();
            String companyn =jTable1.getValueAt(row, 1).toString();
            companyname.setSelectedItem(companyn);
            shipname.setSelectedItem(ship_s);
            fromseaport.setSelectedItem(f_seaport);
            toseaport.setSelectedItem(t_seaport);
        } catch (ParseException ex) {
            Logger.getLogger(info_trip.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void loadwieght1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadwieght1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loadwieght1MouseClicked

    private void loadwieght1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadwieght1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadwieght1ActionPerformed

    private void dateeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateeMouseClicked

    private void dateeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateeActionPerformed

    private void clockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clockMouseClicked

    private void clockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clockActionPerformed

    private void Add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseClicked
        // TODO add your handling code here:
        if(trip.getText().length()==0 || loadwieght1.getText().length()==0 || Date_E.getDate().equals("") || Date_S.getDate().equals("")){
            labMessage.setText("please fill fields ! ");
        }else{
        setvalues();
        t.Add(labMessage);
         }
    }//GEN-LAST:event_Add1MouseClicked

    private void Add1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseEntered
        // TODO add your handling code here:
        setcolor(Add1);
    }//GEN-LAST:event_Add1MouseEntered

    private void Add1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseExited
        // TODO add your handling code here:
        resetcolor(Add1);
    }//GEN-LAST:event_Add1MouseExited
      Connection conn ;
      PreparedStatement s;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info_trip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info_trip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add1;
    private javax.swing.JLabel Back;
    private com.toedter.calendar.JDateChooser Date_E;
    private com.toedter.calendar.JDateChooser Date_S;
    private javax.swing.JTextField Search;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JRadioButton br3;
    private javax.swing.JRadioButton br4;
    private javax.swing.JPanel clear;
    private static javax.swing.JTextField clock;
    private javax.swing.JComboBox<String> companyname;
    private static javax.swing.JTextField datee;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel exit1;
    private javax.swing.JComboBox<String> fromseaport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labMessage;
    private javax.swing.JTextField loadwieght1;
    private javax.swing.JLabel search;
    private javax.swing.JLabel search_by;
    private javax.swing.JComboBox<String> shipname;
    private javax.swing.JPanel showwal;
    private javax.swing.JTextField time;
    private javax.swing.JRadioButton timebr;
    private javax.swing.JComboBox<String> toseaport;
    private javax.swing.JTextField trip;
    private javax.swing.JRadioButton tripno;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables

   

   
}
