/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Interface_Imp.employee;
import Interface_Imp.trip;
import Interface_Imp.workin;
import database.UseDatabase;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import systemmanagmentship.Tools;

/**
 *
 * @author User
 */
public class workOnShip extends javax.swing.JFrame {

    /**
     * Creates new form workOnShip
     */
    public workOnShip() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        search_by = new javax.swing.JLabel();
        search = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        tripno = new javax.swing.JRadioButton();
        nameship = new javax.swing.JRadioButton();
        nameemp = new javax.swing.JRadioButton();
        type = new javax.swing.JRadioButton();
        number = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tripnumber = new javax.swing.JComboBox<>();
        shipname = new javax.swing.JComboBox<>();
        nameemployee = new javax.swing.JComboBox<>();
        typejob = new javax.swing.JComboBox<>();
        update = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        delet = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        showadd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labMessage = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        clear1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_work = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 139));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 139));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 213, 252));
        jLabel1.setText("Trip No:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 28));

        jLabel2.setBackground(new java.awt.Color(0, 0, 139));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 213, 252));
        jLabel2.setText("Name Ship :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 35));

        jLabel3.setBackground(new java.awt.Color(0, 0, 139));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 213, 252));
        jLabel3.setText("Type Job :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 109, 29));

        jLabel4.setBackground(new java.awt.Color(0, 0, 139));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 213, 252));
        jLabel4.setText("Name Employee :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 122, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Cancelnn_32.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 11, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Go_Back_32.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Minusjj_32.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel2.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 11, -1, -1));

        search_by.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_S_32.png"))); // NOI18N
        search_by.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_by.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_byMouseClicked(evt);
            }
        });
        jPanel2.add(search_by, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 63, -1, 35));

        search.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        search.setForeground(new java.awt.Color(210, 213, 252));
        search.setText("Search By :");
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 100, 29));

        search1.setBackground(new java.awt.Color(0, 0, 139));
        search1.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        search1.setForeground(new java.awt.Color(255, 255, 255));
        search1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 213, 252), 2));
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel2.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 63, 211, 35));

        tripno.setBackground(new java.awt.Color(0, 0, 139));
        tripno.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        tripno.setForeground(new java.awt.Color(210, 213, 252));
        tripno.setSelected(true);
        tripno.setText("Trip No");
        jPanel2.add(tripno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        nameship.setBackground(new java.awt.Color(0, 0, 139));
        nameship.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        nameship.setForeground(new java.awt.Color(210, 213, 252));
        nameship.setText("Name Ship");
        nameship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameshipActionPerformed(evt);
            }
        });
        jPanel2.add(nameship, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, 30));

        nameemp.setBackground(new java.awt.Color(0, 0, 139));
        nameemp.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        nameemp.setForeground(new java.awt.Color(210, 213, 252));
        nameemp.setText("Name employee");
        jPanel2.add(nameemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        type.setBackground(new java.awt.Color(0, 0, 139));
        type.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        type.setForeground(new java.awt.Color(210, 213, 252));
        type.setText("Type Top");
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        number.setEditable(false);
        number.setBackground(new java.awt.Color(0, 0, 139));
        number.setFont(new java.awt.Font("Comic Sans MS", 2, 15)); // NOI18N
        number.setForeground(new java.awt.Color(255, 255, 255));
        number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 213, 252), 2, true));
        number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberMouseClicked(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel2.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 168, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 139));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(210, 213, 252));
        jLabel5.setText("number :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 109, 40));

        tripnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(tripnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 168, 30));

        shipname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(shipname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 168, 30));

        nameemployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(nameemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 168, 30));

        typejob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(typejob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 168, 30));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Change_Us.png_48.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 139));
        jLabel8.setText("Update");

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(37, 37, 37))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        delet.setBackground(new java.awt.Color(255, 255, 255));
        delet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        delet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Denied_48.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 139));
        jLabel10.setText("Delete");

        javax.swing.GroupLayout deletLayout = new javax.swing.GroupLayout(delet);
        delet.setLayout(deletLayout);
        deletLayout.setHorizontalGroup(
            deletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(deletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        deletLayout.setVerticalGroup(
            deletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        showadd.setBackground(new java.awt.Color(255, 255, 255));
        showadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        showadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showaddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showaddMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_Account_48.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 139));
        jLabel12.setText("Show All");

        javax.swing.GroupLayout showaddLayout = new javax.swing.GroupLayout(showadd);
        showadd.setLayout(showaddLayout);
        showaddLayout.setHorizontalGroup(
            showaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showaddLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(showaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        showaddLayout.setVerticalGroup(
            showaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showaddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Broom_48.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 139));
        jLabel14.setText("Clear");

        javax.swing.GroupLayout clearLayout = new javax.swing.GroupLayout(clear);
        clear.setLayout(clearLayout);
        clearLayout.setHorizontalGroup(
            clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clearLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37))
        );
        clearLayout.setVerticalGroup(
            clearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        labMessage.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        labMessage.setForeground(new java.awt.Color(0, 0, 139));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Add_User_Male_48.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 139));
        jLabel16.setText(" ADD");

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        clear1.setBackground(new java.awt.Color(255, 255, 255));
        clear1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 139)));
        clear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clear1MouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Prin_48.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 3, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 139));
        jLabel18.setText("Print");

        javax.swing.GroupLayout clear1Layout = new javax.swing.GroupLayout(clear1);
        clear1.setLayout(clear1Layout);
        clear1Layout.setHorizontalGroup(
            clear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clear1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(clear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clear1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clear1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(48, 48, 48))))
        );
        clear1Layout.setVerticalGroup(
            clear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clear1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTable_Display_work.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jTable_Display_work.setForeground(new java.awt.Color(0, 0, 139));
        jTable_Display_work.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "number", "trip No", "Employee name", "Ship name", "Type Job"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Display_work.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_Display_work.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable_Display_work.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_workMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_work);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    trip t = new trip();
    employee emp = new employee();
    workin w = new workin();
    void setvalues(){
//      String empname = choice3.getSelectedItem();
//      String tripno = choice1.getSelectedItem();
//      
      w.setEmpname((String) nameemployee.getSelectedItem());
      w.setTripno(Integer.parseInt(tripnumber.getSelectedItem().toString()));
      w.setShipname((String) shipname.getSelectedItem());
      w.setTypejob((String) typejob.getSelectedItem());
      w.setNumber( Integer.parseInt(number.getText()));

    }
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);//أخفاء النافدة عن الشاشة
    }//GEN-LAST:event_minMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new FromAdmin1());
    }//GEN-LAST:event_backMouseClicked
    int xx , xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();//بش نخلي شاشة تتحرك 
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        this.setOpacity((float) 0.2);//بش نخلي شاشة لما نظغط عليها تصبح شفافة
        xx = evt.getX();
        xy = evt.getX();
   }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
         this.setOpacity((float) 1.0);
    }//GEN-LAST:event_formMouseReleased

    private void search_byMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_byMouseClicked
        // TODO add your handling code here:
        String sreach = "select * from workin where  ";
        if(tripno.isSelected()){
            sreach += "tripno";
        } else if (nameship.isSelected()){
            sreach += "ship_name" ;
        } 
        else if (nameemp.isSelected()){
            sreach += "empname";   
        } else {
            sreach += "typejob ";
        }
        sreach += " like '%" + search1.getText() + "%'";
        database.UseDatabase.fillJTable(sreach, jTable_Display_work);
    }//GEN-LAST:event_search_byMouseClicked

    private void nameshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameshipActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        bg.add(nameemp);
        bg.add(nameship);
        bg.add(type);
        bg.add(tripno);
        database.UseDatabase.fillJTable("select * from workin where Active=1", jTable_Display_work);
        jTable_Display_work.getTableHeader().setReorderingAllowed(false);
        UseDatabase.filComboBox("select trip_no from trip where Active =1 ",tripnumber );
        UseDatabase.filComboBox("select shipname from trip where Active = 1 ",shipname);
        UseDatabase.filComboBox("select empname from employee where Active =1 and workinship=0 ", nameemployee);
        UseDatabase.filComboBox("select TYPEJOP from employee where Active = 1 ",typejob);
        String numb = w.GetAutoNumber();
            number.setText(numb);
    }//GEN-LAST:event_formWindowOpened
    public void setcolor(JPanel panel){
        panel.setBackground(new java.awt.Color(210,209,235));
    }
    public void resetcolor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,255,255));
    }
    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        setvalues();
        w.Update(labMessage);
         database.UseDatabase.fillJTable("select * from workin where Active=1", jTable_Display_work);
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        setcolor(update);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        resetcolor(update);
    }//GEN-LAST:event_updateMouseExited

    private void deletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletMouseEntered
        // TODO add your handling code here:
        setcolor(delet);
    }//GEN-LAST:event_deletMouseEntered

    private void deletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletMouseExited
        // TODO add your handling code here:
        resetcolor(delet);
    }//GEN-LAST:event_deletMouseExited

    private void showaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showaddMouseEntered
        // TODO add your handling code here:
          setcolor(showadd);
    }//GEN-LAST:event_showaddMouseEntered

    private void showaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showaddMouseExited
        // TODO add your handling code here:
      resetcolor(showadd);
    }//GEN-LAST:event_showaddMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        resetcolor(clear);
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        setcolor(clear);
    }//GEN-LAST:event_clearMouseEntered

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void deletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletMouseClicked
      setvalues();
      w.Delete(labMessage);
       database.UseDatabase.fillJTable("select * from workin where Active=1", jTable_Display_work);
    }//GEN-LAST:event_deletMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        labMessage.setText("");
        search1.setText("");
        add.setEnabled(true);
        update.setEnabled(false);
        delet.setEnabled(false);
        String numb = w.GetAutoNumber();
            number.setText(numb);
    }//GEN-LAST:event_clearMouseClicked

    private void jTable_Display_workMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_workMouseClicked
        int row = jTable_Display_work.getSelectedRow();
        String C_Number = jTable_Display_work.getValueAt(row, 0).toString();
        
        number.setText(C_Number);
            String _tripno = jTable_Display_work.getValueAt(row, 1).toString();
            String employee =jTable_Display_work.getValueAt(row, 2).toString();
            String ship = jTable_Display_work.getValueAt(row, 3).toString();
            String _type =jTable_Display_work.getValueAt(row, 4).toString();
            tripnumber.setSelectedItem(_tripno);
            shipname.setSelectedItem(ship);
            nameemployee.setSelectedItem(employee);
            typejob.setSelectedItem(_type);
        add.setEnabled(false);
    }//GEN-LAST:event_jTable_Display_workMouseClicked

    private void showaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showaddMouseClicked
        // TODO add your handling code here:
         database.UseDatabase.fillJTable("select * from workin where Active=1", jTable_Display_work);
    }//GEN-LAST:event_showaddMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        setvalues();
        w.Add(labMessage);
         database.UseDatabase.fillJTable("select * from workin where Active=1", jTable_Display_work);
        
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
        setcolor(add);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        resetcolor(add);
    }//GEN-LAST:event_addMouseExited

    private void numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_numberMouseClicked

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void clear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseClicked
        try {
            // TODO add your handling code here:
            MessageFormat header = new MessageFormat("Report to Employees working on Ships" +"\n");
            MessageFormat footer = new MessageFormat("Page - {0}");
            jTable_Display_work.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (PrinterException ex) {
            Logger.getLogger(workOnShip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clear1MouseClicked

    private void clear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseEntered
        // TODO add your handling code here:
        setcolor(clear1);
    }//GEN-LAST:event_clear1MouseEntered

    private void clear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseExited
        // TODO add your handling code here:
        resetcolor(clear1);
    }//GEN-LAST:event_clear1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workOnShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workOnShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workOnShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workOnShip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workOnShip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JPanel clear;
    private javax.swing.JPanel clear1;
    private javax.swing.JLabel close;
    private javax.swing.JPanel delet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_work;
    private javax.swing.JLabel labMessage;
    private javax.swing.JLabel min;
    private javax.swing.JRadioButton nameemp;
    private javax.swing.JComboBox<String> nameemployee;
    private javax.swing.JRadioButton nameship;
    private javax.swing.JTextField number;
    private javax.swing.JLabel search;
    private javax.swing.JTextField search1;
    private javax.swing.JLabel search_by;
    private javax.swing.JComboBox<String> shipname;
    private javax.swing.JPanel showadd;
    private javax.swing.JRadioButton tripno;
    private javax.swing.JComboBox<String> tripnumber;
    private javax.swing.JRadioButton type;
    private javax.swing.JComboBox<String> typejob;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
